print("How old are you?", end=' ')
age = input()
print("You choose Sony or Microsoft?", end=' ')
Choose = input()
print("Are you like video games?", end=' ')
video_games = input("Yes or NO?")
print("中文測試行", end=' ')
China = input("是否看得見中文,是否能使用中文輸入")

print(f"{age}  ,{Choose} , {video_games} {China} ")
